export const SET_SHOPMATH = 'SET_SHOPMATH'
export const GET_FOODINFO = 'GET_FOODINFO'
export const SET_SHOPINFO = 'SET_SHOPINFO'
export const SET_DOM = 'SET_DOM'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_BOOLEAN = 'SET_BOOLEAN'
export const SET_ALL_NUM = 'SET_ALL_NUM'
export const SET_ALL_SUM = 'SET_ALL_SUM'
